#! /bin/sh

bspc config border_width                1
bspc config window_gap                  6
bspc config top_padding                 15

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true

bspc monitor -d 0 1 2 3 4 5 6

bspc config focused_border_color        '#003365'
bspc config normal_border_color         '#001326'

panel &
redshift -c .config/redshift.conf &
