#! /bin/sh

bspc config border_width        2
bspc config window_gap          7
bspc config top_padding	       21

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5 6 7

focused_border_color #276324
normal_border_color #051C04

panel &
redshift -c .config/redshift.conf &
