#! /bin/sh

bspc config border_width                1
bspc config window_gap                  6
bspc config top_padding                 15

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config focused_border_color        '#AD9152'
bspc config normal_border_color         '#191F31'

panel &
redshift -c .config/redshift.conf &
